### ISSUE TITLE
Schema Format. 

### ISSUE THREAD

**Issue by sajjadjaved01** [10play/10tap-editor#101]
Hi, i have a editor Slate.js 
running in production, it gives me only output as JSON.

And 10Tap accepts json but both of them have different json schema .

Is there a way to customize the JSON Schema format according my needs.

**Comment by 17Amir17** [comment]
This might help you https://10play.github.io/10tap-editor/docs/examples/configureExtensions#extending-extension-and-updating-document-schema

Otherwise I think you should create some migration function to migrate from slate

You can also create a fully customizable tiptap editor with https://10play.github.io/10tap-editor/docs/setup/advancedSetup
