### ISSUE TITLE
onReadOnlyChecked in TaskListBridge (TaskItem)

### ISSUE THREAD

**Issue by jinwon7878** [10play/10tap-editor#131]
Hi! I'm having a great time implementing your editor, and thank you for always being so quick to respond.

I'd like to pass onReadOnlyChecked to configure, so that the TaskItem can be checked when the editor is used with editable : false. This could be a key feature for my project, as it would definitely make the “check” function more usable for users.

[https://tiptap.dev/docs/editor/api/nodes/task-item#on-read-only-checked](https://tiptap.dev/docs/editor/api/nodes/task-item#on-read-only-checked)

Currently, passing it to configureExtension of TaskListBridge doesn't seem to be supported (is it because onReadOnlyChecked is the configure attribute of TaskItem?), so I'm wondering if this is something I'd need to work around personally with an advanced setup, or if there's an update planned?

Thanks as always :)

**Comment by GuySerfaty** [comment]
Hi, @jinwon7878  again! love to hear you have a great time with 10tap, unfortunately, I think even with adding  [onReadOnlyChecked](https://tiptap.dev/docs/editor/api/nodes/task-item#on-read-only-checked) functionality you wouldn't be able to know which task item changed because of [this issue](https://github.com/ueberdosis/tiptap/issues/3676), Im open to add onReadOnlyChecked if you have a good way to "know" which node changed, it can be an important improvement to our lib
