### ISSUE TITLE
[BUG]: Props in RichText component not working (e.g. showsVerticalScrollIndicator)

### ISSUE THREAD

**Issue by davekooi** [10play/10tap-editor#178]
**Describe the bug**
It looks like the RichText component accepts different props to customize the appearance. I'm trying to remove the vertical scroll indicators using the showsVerticalScrollIndicator prop but setting this prop to false does not seem to remove the scroll indicators. I'm also trying to set custom content insets using the contentInset prop but that also does not seem to make difference.

**To Reproduce**
On iOS,
`<RichText editor={editor} showsVerticalScrollIndicator={false}/>`
Setting showsVerticalScrollIndicator to false and true seems to not make a difference (scroll indicators still showing in either case).

**Expected behavior**
Vertical scroll indicators should not appear when showsVerticalScrollIndicator is false.

**Screenshots**
Testing on iPhone simulator.
<img width="327" alt="Screenshot 2024-08-01 at 4 32 54 PM" src="https://github.com/user-attachments/assets/cf76562b-9c54-457a-8cf8-41eb9e5c0c31">

**Comment by 17Amir17** [comment]
We expose all props from the original WebView component (since RichText is just a wrapper above a WebView)

If the scroll is coming from within the webview you can inspect it with safari/chrome: https://github.com/react-native-webview/react-native-webview/blob/master/docs/Debugging.md#debugging-webview-contents
And inject custom css to remove the scroll https://10play.github.io/10tap-editor/docs/examples/customCss#addingoverriding-css
