### ISSUE TITLE
[BUG]: select text very difficult

### ISSUE THREAD

**Issue by uongsuadaubung** [10play/10tap-editor#184]
**Describe the bug**
In the video I have a TextInput above and an Editor below. Inside the TextInput, moving the cursor to select text is very easy. Selecting text in the Editor is very difficult because it always loses focus. When I only drag the cursor a few words, it disappears.

**To Reproduce**

1. Select text
2. Move the cursor

**Expected behavior**
Moving the cursor to select text was as easy as TextInput

**Screen record**

https://github.com/user-attachments/assets/5f198ce1-ff55-45d2-b49d-c63e4bfaebe5

**Comment by GuySerfaty** [comment]
hey @uongsuadaubung thanks for report this, I see where the issue is, is because of we adding highlight bgcolor when you selected text so when you change the context to something out of the webview editor the user will still see what text it edit,

on android this highlight is not important as in iOS, android seems to still show you selected text even without our fix:
![image](https://github.com/user-attachments/assets/883d4ce9-d66e-4bc9-86a3-6805531baab8)

so as you can see the selection still there even if the cursor move to the link input on the toolbar

Im going to disable it on android by default and add a prop to `useEditorBridge` so ppl will be able to control if they want it or not
