### ISSUE TITLE
How to add Tiptap Mathematics Pro extension?

### ISSUE THREAD

**Issue by rustyonrampage** [10play/10tap-editor#195]
I am trying to integrate Tiptap [mathematics extension](https://tiptap.dev/docs/editor/extensions/functionality/mathematics) but have no idea how it can be done.

Just for testing purposes. I added an extension in the node_modules.  After that  I added this extension to the editor bridges also in the node_modules file. If I console.log the useEditorBridge instance in my app, I can see the bridge in it.  However, when I pass some katex, it doesn't gets rendered.
There is also a question about how can I like this extension with a toolbar button. I couldn't see any commands in the math extension so I don't understand how to trigger it in the editor.

<img width="267" alt="image" src="https://github.com/user-attachments/assets/303a04f5-e25d-4426-95a5-febea95fb713">

`import Mathematics from "@tiptap-pro/extension-mathematics"
import BridgeExtension from "./base"

export const MathBridge = new BridgeExtension({
    tiptapExtension: Mathematics,
    onBridgeMessage: (editor, message) => {
        return false
    },
    extendEditorInstance: (sendBridgeMessage) => {
        return {
            toggleMathematics: () =>
              sendBridgeMessage({
                type: 'toggle-mathematics',
              }),
          };
    },
    extendEditorState: (editor) => {
        return {}
    },
   })`

**Comment by 17Amir17** [comment]
Hey @rustyonrampage,
In order to add your own bridge you need to use the [Advanced Setup](https://10play.github.io/10tap-editor/docs/setup/advancedSetup).

We have some pro examples where we utilize the advanced setup to create custom bridges for other tiptap extensions for example: [mentions](https://10play.github.io/10tap-editor/docs/examples/mentions), [comments](https://10play.github.io/10tap-editor/docs/examples/comments). Feel free to contact us at email@10play.dev
