### ISSUE TITLE
Italic deactivates when backspacing from second line to first while bold remains active

### ISSUE THREAD

**Issue by SecYJ** [10play/10tap-editor#212]
When I activate both bold and italic on the second line and then press backspace to move back to the first line (where bold is already active), the italic formatting becomes inactive while bold stays active. Expected behavior is for italic to remain active along with bold when moving between lines.

I am using advanced setup with the following extensions from tiptap

- Document
- Paragraph
- Text
- HardBreak
- Character count

Any solution or suggest a workaround for preserving the italic formatting when moving between lines?

https://github.com/user-attachments/assets/fdb888fc-ed94-42d1-be61-32c398f94292

**Comment by 17Amir17** [comment]
Hey!
TenTap uses Tiptap (prosemirror) behind the scenes, and this is the default behaviour. Since you are using the advanced setup you could maybe write some custom logic to keep italic active once it is pressed, but this will require some tiptap/prosemirror knowledge

https://github.com/user-attachments/assets/5418fd81-71d8-4f2e-9f08-5643e61cc625
