### ISSUE TITLE
[BUG]: Get content is waiting long time while keeping press button remove and unpress

### ISSUE THREAD

**Issue by TuHuynh296** [10play/10tap-editor#253]
**Describe the bug**
Get content is waiting long time while keeping press button remove and unpress

**To Reproduce**
1. Init component 10tap editor
2. Typing some thing is too long
3. Keep button remove
4. Check log content will be showed with time (Screenshots)

**Expected behavior**
I want the log content of useEditorContent should show immediately instead of waiting long time up to over 9 seconds, please see the Screenshots below to check
**Screenshots**
1. Assume I have sentence in the component RichText of tentap-editor:
![image](https://github.com/user-attachments/assets/6958a205-8b6e-4aea-aa8d-0de400522e38)
2. The setup of editor and editorContent is:
![image](https://github.com/user-attachments/assets/a0fb973e-6100-4895-9d2d-be827c4ad894)
3. My useEffect log value and time received of useContent is:
![image](https://github.com/user-attachments/assets/0b104f5b-2be5-45d6-9e4e-c29a17dd7c9c)
4. While I keep button remove and unpress to "here is the ":
![image](https://github.com/user-attachments/assets/a770e9e5-9784-4a20-ac1f-1ba3da1217d2).
![image](https://github.com/user-attachments/assets/418e9bb7-fe31-4cc9-9cf5-66ced003a2e4)
6. The log is showed:
![image](https://github.com/user-attachments/assets/3c6ec987-e8ec-4f43-a0d5-48cab3bd1a65)
The time I press and unpress aproximately upto 2.5 seconds but the log time is showing that the content of useEditorContent is waiting for long time up to over 9 seconds. I cannot get content immediately if user run to unmount component and want to save value such as the UI showed on screen of device. If user only remove some character without keep press, it work well for get content immediately.

**Comment by 17Amir17** [comment]
Unfortunately this is the downside with WebView based rich text editors - because the rich text lives within a webview the communication is async, unless there is somehow a way to make the communication synchronous I do not see a way to fix this.
However 9 seconds does sound like allot, which is worth looking into
I would probably try getting the content with `editor.getHTML` and then after it resolves unmount, and if that feels choppy, try keep it mounted in the background while moving away
